//	R0Q2/daniel/20220505
"use strict";

const { Configuration } = require("-/pb/natalis/012/Configuration.js");

module.exports =

class UnitTests_Configuration
{
	//	Category: Unit test
	//	Function: Run unit tests for selected class methods.
	static unitTest_Configuration(result)
	{
		const test = (outcome, expected) => JSON.stringify(outcome) === JSON.stringify(expected);
		const fail = (testName, expected, outcome) => ({ testName, expected, outcome, expectedJSON: JSON.stringify(expected), outcomeJSON: JSON.stringify(outcome) });

		let obj;
		let expected;
		let outcome;

		//	Configuration.flatten
		obj = {}; expected = {}; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: 1 }; expected = { a: 1 }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: { b: 1 } }; expected = { "a.b": 1 }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [] }; expected = { a: [] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [{}] }; expected = { a: [{}] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [100] }; expected = { "a[]": 100, a: [100] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [101, 102, 103] }; expected = { "a[]": 103, a: [101, 102, 103] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [{ b: 100 }] }; expected = { "a[].b": 100, a: [{ b: 100 }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [{ b: 101 }, { b: 102 }, { b: 103 }] }; expected = { "a[].b": 103, a: [{ b: 101 }, { b: 102 }, { b: 103 }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [{ b: 101, c: 102 }] }; expected = { "a[].b": 101, "a[].c": 102, a: [{ b: 101, c: 102 }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: [{ b: 101, c: 102 }, { c: 103, d: 104 }] }; expected = { "a[].b": 101, "a[].c": 103, "a[].d": 104, a: [{ b: 101, c: 102 }, { c: 103, d: 104 }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: 101, b: 102 }; expected = { a: 101, b: 102 }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: { b: [] } }; expected = { "a.b": [] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: { b: [{ c: 100 }] } }; expected = { "a.b[].c": 100, "a.b": [{ c: 100 }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: { b: [{ c: 101 }, { c: 102 }] } }; expected = { "a.b[].c": 102, "a.b": [{ c: 101 }, { c: 102 }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: { b: [{ c: [] }] } }; expected = { "a.b[].c": [], "a.b": [{ c: [] }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));
		obj = { a: { b: [{ c: [{ d: 101 }, { d: 102 }] }] } }; expected = { "a.b[].c[].d": 102, "a.b[].c": [{ d: 101 }, { d: 102 }], "a.b": [{ c: [{ d: 101 }, { d: 102 }] }] }; if (!test(outcome = Configuration.flatten(obj), expected)) result.push(fail(`flatten(${JSON.stringify(obj)})`, expected, outcome));

		//	Configuration.mergeString
		let text;
		let dict;
		text = ""; dict = {}; expected = { value: "", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "a"; dict = {}; expected = { value: "a", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{"; dict = {}; expected = { value: "{", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{"; dict = {}; expected = { value: "{{", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{a"; dict = {}; expected = { value: "{{a", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{{"; dict = {}; expected = { value: "{{{", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{}"; dict = {}; expected = { value: "{{}", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{a}"; dict = {}; expected = { value: "{{a}", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{}}"; dict = {}; expected = { value: "{{}}", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{a}}"; dict = { a: 1 }; expected = { value: "1", mergeKeys: { a: true }, mergeCount: 1 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{{{a}}}}"; dict = { "{{a": 1 }; expected = { value: "1}}", mergeKeys: { "{{a": true }, mergeCount: 1 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{$oparen}}"; dict = {}; expected = { value: "{", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{$oparen}}{{$oparen}}}}"; dict = {}; expected = { value: "{{}}", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{$oparen}}{{$oparen}}a}}"; dict = {}; expected = { value: "{{a}}", mergeKeys: {}, mergeCount: 0 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "1{{a}}2"; dict = { a: 3 }; expected = { value: "132", mergeKeys: { a: true }, mergeCount: 1 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "1{{a}}2"; dict = { a: "{{a}}" }; expected = { value: "1{{a}}2", mergeKeys: { a: true }, mergeCount: 1 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "1{{a}}2{{b}}3{{c}}4"; dict = { a: "a", b: "b", c: "c" }; expected = { value: "1a2b3c4", mergeKeys: { a: true, b: true, c: true }, mergeCount: 3 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{a}}{{b}}{{c}}"; dict = { a: "a", b: "b", c: "c" }; expected = { value: "abc", mergeKeys: { a: true, b: true, c: true }, mergeCount: 3 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));
		text = "{{a}}{{b}}{{c}}{{b}}"; dict = { a: "a", b: "b", c: "c" }; expected = { value: "abcb", mergeKeys: { a: true, b: true, c: true }, mergeCount: 4 }; if (!test(outcome = Configuration.mergeString(text, dict), expected)) result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome));

		text = "{{{}}"; dict = {}; try { Configuration.mergeString(text, dict); result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		text = "{{{}}}"; dict = {}; try { Configuration.mergeString(text, dict); result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		text = "{{a}}"; dict = {}; try { Configuration.mergeString(text, dict); result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		text = "{{{{a}}}}"; dict = { "{{a}}": 1 }; try { Configuration.mergeString(text, dict); result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		text = "1{{a}}2"; dict = {}; try { Configuration.mergeString(text, dict); result.push(fail(`mergeString(${JSON.stringify(text)}, ${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }

		//	Configuration.processSettingReferences
		dict = {}; expected = {}; if (!test(outcome = Configuration.processSettingReferences(dict), expected)) result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome));
		dict = { a: "" }; expected = { a: "" }; if (!test(outcome = Configuration.processSettingReferences(dict), expected)) result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome));
		dict = { a: 1, b: "{{a}}" }; expected = { a: 1, b: "1" }; if (!test(outcome = Configuration.processSettingReferences(dict), expected)) result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome));
		dict = { a: 1, b: "{{c}}", c: "{{a}}" }; expected = { a: 1, c: "1", b: "1" }; if (!test(outcome = Configuration.processSettingReferences(dict), expected)) result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome));
		dict = { a: "{{a}}" }; try { Configuration.processSettingReferences(dict); result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		dict = { a: "{{b}}", b: "{{a}}" }; try { Configuration.processSettingReferences(dict); result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		dict = { a: "{{b}}", b: "{{c}}", c: "{{a}}" }; try { Configuration.processSettingReferences(dict); result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }
		dict = { a: "{{b}}", b: "{{c}}", c: "{{b}}" }; try { Configuration.processSettingReferences(dict); result.push(fail(`Configuration.processSettingReferences(${JSON.stringify(dict)})`, expected, outcome)); } catch (ex) { }

		//	Configuration.load
		let main;
		let snippets;
		let environment;
		//	Configuration.load - basic
		main = { json: {}, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: {}, client: { environment: "env" }, environment: "env" }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: {} }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: {}, client: { environment: "env" }, environment: "env" }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: "required" }, common: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { a: 1 }, client: { environment: "env" }, environment: "env", a: 1 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: { b: "required" } }, common: { a: { b: 1 } } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "a.b": 1 }, client: { environment: "env" }, environment: "env", a: { b: 1 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: ["required"] }, common: { a: [1] } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "a": [1], "a[]": 1 }, client: { environment: "env" }, environment: "env", a: [1] }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: ["required"] }, common: { a: [1, 2] } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "a": [1, 2], "a[]": 2 }, client: { environment: "env" }, environment: "env", a: [1, 2] }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: [{ b: "required", c: "required" }] }, common: { a: [{ b: 1, c: 2 }] } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "a": [{ b: 1, c: 2 }], "a[].b": 1, "a[].c": 2 }, client: { environment: "env" }, environment: "env", a: [{ b: 1, c: 2 }] }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: "required" }, env: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { a: 1 }, client: { environment: "env" }, environment: "env", a: 1 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: "required" }, common: { a: 2 }, env: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { a: 1 }, client: { environment: "env" }, environment: "env", a: 1 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: "required" }, common: { a: 2 }, env2: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { a: 2 }, client: { environment: "env" }, environment: "env", a: 2 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { __proto__: { polluted: "required" } }, common: { __proto__: { polluted: true } } }, name: "configuration.json" }; snippets = []; environment = "env"; outcome = Configuration.load(main, snippets, environment); if ({}.polluted) result.push(fail(`Configuration.load - prototype pollution`, "undefined", outcome.length));
		//	Configuration.load - groups
		main = { json: { group: { schema: {} } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: {}, client: { environment: "env" }, environment: "env" }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { a: "required" }, common: { a: 1 } } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "group.a": 1 }, client: { environment: "env" }, environment: "env", group: { a: 1 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { a: "required" }, env: { a: 1 } } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "group.a": 1 }, client: { environment: "env" }, environment: "env", group: { a: 1 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { a: "required" }, common: { a: 2 }, env: { a: 1 } } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "group.a": 1 }, client: { environment: "env" }, environment: "env", group: { a: 1 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { a: "required" }, common: { a: 2 }, env2: { a: 1 } } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { "group.a": 2 }, client: { environment: "env" }, environment: "env", group: { a: 2 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { __proto__: { polluted: "required" } }, common: { __proto__: { polluted: true } }, env2: { __proto__: { polluted: true } } } }, name: "configuration.json" }; snippets = []; environment = "env2"; outcome = Configuration.load(main, snippets, environment); if ({}.polluted) result.push(fail(`Configuration.load - prototype pollution (2)`, "undefined", outcome.length));
		//	Configuration.load - snippets
		main = { json: {}, name: "configuration.json" }; snippets = [{ json: {}, name: "snippet.json" }]; environment = "env"; expected = { all: {}, client: { environment: "env" }, environment: "env" }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: {} }, name: "configuration.json" }; snippets = [{ json: {}, name: "snippet.json" }]; environment = "env"; expected = { all: {}, client: { environment: "env" }, environment: "env" }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: "required" } }, name: "configuration.json" }; snippets = [{ json: { common: { a: 1 } }, name: "snippet.json" }]; environment = "env"; expected = { all: { a: 1 }, client: { environment: "env" }, environment: "env", a: 1 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { schema: { a: "required" }, common: { a: 2 } }, name: "configuration.json" }; snippets = [{ json: { common: { a: 1 } }, name: "snippet.json" }]; environment = "env"; expected = { all: { a: 1 }, client: { environment: "env" }, environment: "env", a: 1 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { a: "required" }, common: { a: 2 } } }, name: "configuration.json" }; snippets = [{ json: { group: { common: { a: 1 } } }, name: "snippet.json" }]; environment = "env"; expected = { all: { "group.a": 1 }, client: { environment: "env" }, environment: "env", group: { a: 1 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { a: "required" }, common: { a: 2 } } }, name: "configuration.json" }; snippets = [{ json: { group: { env: { a: 1 } } }, name: "snippet.json" }]; environment = "env"; expected = { all: { "group.a": 1 }, client: { environment: "env" }, environment: "env", group: { a: 1 } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		main = { json: { group: { schema: { __proto__: { polluted: "required" } }, common: { __proto__: { polluted: true } }, env2: { __proto__: { polluted: true } } } }, name: "configuration.json" }; snippets = [{ json: { group: { env: { __proto__: { polluted: true } } } }, name: "snippet.json" }]; environment = "env2"; outcome = Configuration.load(main, snippets, environment); if ({}.polluted) result.push(fail(`Configuration.load - prototype pollution (2)`, "undefined", outcome.length));
		//	Configuration.load - references
		main = { json: { group1: { schema: { a: "required" }, common: { a: "{{group2.b}}" } }, group2: { schema: { b: "required" } } }, name: "configuration.json" }; snippets = [{ json: { group2: { common: { b: 1 } } }, name: "snippet.json" }]; environment = "env"; expected = { all: { "group2.b": 1, "group1.a": "1" }, client: { environment: "env" }, environment: "env", group2: { b: 1 }, group1: { a: "1" } }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		//	Configuration.load - client
		main = { json: { schema: { a: "required" }, clientExport: ["a"], common: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = { all: { a: 1 }, client: { environment: "env", a: 1 }, environment: "env", a: 1 }; if (!test(outcome = Configuration.load(main, snippets, environment), expected)) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)})`, expected, outcome));
		//	Configuration.load - exceptions (non-exhaustive)
		main = { json: { a: 1 }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x71D0B7 Configuration group schema is missing: "configuration.json::a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x217BFD Configuration validation failed: "configuration.json[env]::<root>". Configuration property is required, see schema. Related configuration field: "a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, a: 1 }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x1BE261 Configuration groups can only contain environment sections, the "common" section and the "clientExport" section: "configuration.json::<root>.a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, common: { b: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x217BFD Configuration validation failed: "configuration.json[env]::<root>". Invalid configuration property, see schema. Related configuration field: "b".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, env2: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x217BFD Configuration validation failed: "configuration.json[env]::<root>". Configuration property is required, see schema. Related configuration field: "a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { group: {} }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x71D0B7 Configuration group schema is missing: "configuration.json::group".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { group: { schema: { a: "required" }, env2: { a: 1 } } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x217BFD Configuration validation failed: "configuration.json[env]::group". Configuration property is required, see schema. Related configuration field: "a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: [{ b: "required", c: "required" }, { b: "required", d: "required" }] } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0xCAFA87 Configuration schema array field definition is invalid: "configuration.json::<root>.a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" } }, name: "configuration.json" }; snippets = [{ json: {}, name: "snippet.json" }]; environment = "env"; expected = `0x217BFD Configuration validation failed: "configuration.json[env]::<root>". Configuration property is required, see schema. Related configuration field: "a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" } }, name: "configuration.json" }; snippets = [{ json: { a: 1 }, name: "snippet.json" }]; environment = "env"; expected = `0x1BE261 Configuration groups can only contain environment sections, the "common" section and the "clientExport" section: "snippet.json::<root>.a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, common: { a: "{{a}}" } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x8A6941 Circular reference: "a".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, common: { a: "{{b}}" } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0xECC25B Key is invalid: "b".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, clientExport: {}, common: { a: 1 } }, name: "configuration.json" }; snippets = []; environment = "env"; expected = `0x93718E Configuration section "clientExport" must be an array: "configuration.json::<root>".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
		main = { json: { schema: { a: "required" }, common: { a: 1 } }, name: "configuration.json" }; snippets = [{ json: { clientExport: ["a"] }, name: "snippet.json" }]; environment = "env"; expected = `0x741F6E Configuration snippet "clientExport" is prohibited: "snippet.json::<root>".`; try { Configuration.load(main, snippets, environment); result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (1)`, new Error(), outcome)); } catch (ex) { if (ex.message !== expected) result.push(fail(`Configuration.load(${JSON.stringify(main)}, ${JSON.stringify(snippets)}, ${JSON.stringify(environment)}) (2)`, expected, ex.message)); }
	}
}

module.exports.UnitTests_Configuration = module.exports;
